# Generated by Django 2.0.5 on 2018-07-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customertype', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
