# Generated by Django 2.0.5 on 2018-07-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0002_auto_20180710_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_username', models.CharField(max_length=40)),
                ('teacher_name', models.CharField(max_length=40)),
                ('teacher_sex', models.CharField(max_length=10)),
                ('teacher_age', models.IntegerField()),
                ('teacher_phone', models.CharField(max_length=40)),
                ('teacher_adress', models.CharField(max_length=200)),
                ('teacher_professional', models.CharField(max_length=500)),
                ('teacher_faculty', models.CharField(max_length=100)),
                ('teacher_profession', models.CharField(max_length=100)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mypage.Users')),
            ],
        ),
    ]
