# Generated by Django 2.0.5 on 2018-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0003_teacherinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseinfo',
            fields=[
                ('course_name', models.CharField(max_length=40)),
                ('course_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('course_number', models.CharField(max_length=40)),
                ('course_attribute', models.CharField(max_length=40)),
                ('course_examtype', models.CharField(max_length=40)),
                ('course_classplace', models.CharField(max_length=400)),
                ('course_classtime', models.CharField(max_length=100)),
                ('course_classweek', models.CharField(max_length=100)),
            ],
        ),
    ]
