# Generated by Django 2.0.5 on 2018-07-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0004_courseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_teachcourse',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
