# Generated by Django 2.0.5 on 2018-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0006_auto_20180719_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_department',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
