# Generated by Django 2.0.5 on 2018-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0007_userinfo_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_college',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
