# Generated by Django 2.0.5 on 2018-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0008_userinfo_user_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=40)),
                ('student_username', models.CharField(max_length=40)),
                ('course_grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=40)),
                ('course_teacher_username', models.CharField(max_length=40)),
                ('course_examtype', models.CharField(max_length=40)),
                ('course_classplace', models.CharField(max_length=400)),
                ('course_classtime', models.CharField(max_length=800)),
                ('course_classweek', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_classplace',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_classtime',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_classweek',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_examtype',
        ),
    ]
