# Generated by Django 2.0.5 on 2018-07-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0009_auto_20180731_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='teacher_teachcourse',
        ),
    ]
