# Generated by Django 2.0.5 on 2018-07-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0010_remove_teacherinfo_teacher_teachcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourse',
            name='course_to_college',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='course_to_department',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
