# Generated by Django 2.0.5 on 2018-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0012_studentcourse_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course_grade',
            field=models.FloatField(default=0),
        ),
    ]
