# Generated by Django 2.0.5 on 2018-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0013_auto_20180802_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='exam_num',
            field=models.IntegerField(default=1),
        ),
    ]
