# Generated by Django 2.0.5 on 2018-08-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0014_studentcourse_exam_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_College',
            fields=[
                ('departmentnumber', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('collegename', models.CharField(default='', max_length=100)),
                ('departmentname', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
