# Generated by Django 2.0.5 on 2018-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0016_classtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroomnum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('classroomname', models.CharField(max_length=200)),
            ],
        ),
    ]
