# Generated by Django 2.0.5 on 2018-08-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0017_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_now', models.CharField(max_length=10)),
                ('tag', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='course_classplace',
        ),
    ]
