# Generated by Django 2.0.5 on 2018-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0018_auto_20180806_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='param',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
