# Generated by Django 2.0.5 on 2018-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0020_auto_20180806_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='term_now',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
