# Generated by Django 2.0.5 on 2018-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0021_auto_20180806_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='ispass',
            field=models.IntegerField(default=0),
        ),
    ]
