# Generated by Django 2.0.5 on 2018-08-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0022_studentcourse_ispass'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercourse',
            name='tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='term',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
