# Generated by Django 2.0.5 on 2018-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mypage', '0012_auto_20180801_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course_grade',
            field=models.FloatField(default=0),
        ),
    ]
